vk_blog:
    resource: "@VKBlogBundle/Resources/config/routing.yml"
    prefix:   /

vk_hello:
    resource: "@VKHelloBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
