post_index:
    path:     /
    defaults: { _controller: "VKBlogBundle:Post:index" }
    methods:  GET

post_show:
    path:     /{id}/show
    defaults: { _controller: "VKBlogBundle:Post:show" }
    methods:  GET
    requirements:
        id:   \d+
post_new:
    path:     /new
    defaults: { _controller: "VKBlogBundle:Post:new" }
    methods:  [GET, POST]

post_edit:
    path:     /{id}/edit
    defaults: { _controller: "VKBlogBundle:Post:edit" }
    methods:  [GET, POST]
    requirements:
        id:   \d+
    
post_delete:
    path:     /{id}/delete
    defaults: { _controller: "VKBlogBundle:Post:delete" }
    methods:  DELETE
    requirements:
        id:   \d+
    